# Generated by Django 5.0.4 on 2024-04-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_items',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
