# Generated by Django 5.0.4 on 2024-04-08 14:07

import django.core.validators
import shoesdepot.app_auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(2, message='Name must be at least 2 characters.'), django.core.validators.MaxLengthValidator(20, message='Name cannot be longer than 20 characters.'), django.core.validators.RegexValidator('^[A-Za-z\\s]+$', message='Name should contain only letters and spaces.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(2, message='Name must be at least 2 characters.'), django.core.validators.MaxLengthValidator(20, message='Name cannot be longer than 20 characters.'), django.core.validators.RegexValidator('^[A-Za-z\\s]+$', message='Name should contain only letters and spaces.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[shoesdepot.app_auth.validators.validate_phone_number]),
        ),
    ]
